CREATE TABLE Users (
    Id INT PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(200) NOT NULL,
    CreatedDate DATETIME NOT NULL
);

CREATE TABLE Products (
    Id INT PRIMARY KEY,
    Name NVARCHAR(150) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    StockQuantity INT NOT NULL,
    CreatedDate DATETIME NOT NULL
);

CREATE TABLE RC (
    Id INT NOT NULL PRIMARY KEY,
    Value NVARCHAR(100) NULL
);
